import { VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "PutMPV";
    width: 480px;
    height: 320px;

    VerticalBox {
        padding: 24px;
        spacing: 12px;

        Text {
            text: "Hello, world!";
            font-size: 28px;
            font-weight: 600;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }
}
